name: Staging CI/CD

on:
  push:
    branches: '**'

env:
  IMAGE_NAME: 'riandyhasan/school-recommendation'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build --platform linux/amd64 -t $(echo $IMAGE_NAME) .

      - name: Push the Docker image
        run: docker push $(echo $IMAGE_NAME)

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Azure Virtual Machine via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            # Login Docker
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            # Pull image
            docker pull riandyhasan/school-recommendation
            # Stop running container
            docker stop yandy-container
            # Remove old container
            docker rm yandy-container
            # Remove dangling image
            docker image prune -a
            yes | head -1
            # Run image and open port
            docker run -d -p 80:5000 --name yandy-container riandyhasan/school-recommendation
